
-- Generated by SQLcl REST Data Services 24.4.4.0
-- Exported REST Definitions from ORDS Schema Version 25.3.1.r2891312
-- Schema: ATI   Date: Mon Mar 16 10:22:04 CET 2026
--
BEGIN
--   ORDS.ENABLE_SCHEMA(
--       p_enabled             => TRUE,
--       p_schema              => 'ATI',
--       p_url_mapping_type    => 'BASE_PATH',
--       p_url_mapping_pattern => 'ati',
--       p_auto_rest_auth      => FALSE);    

  ORDS.DEFINE_MODULE(
      p_module_name    => 'com.dbflow.deploy',
      p_base_path      => '/dbflow/deploy/',
      p_items_per_page =>  25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'com.dbflow.deploy',
      p_pattern        => 'compile',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.dbflow.deploy',
      p_pattern        => 'compile',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'declare
    l_response  json_object_t := json_object_t();
begin
    -- set Content-Type to JSON explicitly
    owa_util.mime_header(''application/json'', false);
    sys.htp.p(''Cache-Control: no-cache'');
    owa_util.http_header_close;

    l_response.put(''success'', true);

    sys.htp.p(l_response.to_string);
end;'
      );
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.dbflow.deploy',
      p_pattern        => 'compile',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'declare
    l_body_blob blob := :body;
    l_content_type varchar2(255) := :content_type;
    l_fname varchar2(4000) := :fname;
begin
  rest_compile.run_payload_rest(p_request_name => l_fname,
                                p_payload      => l_body_blob,
                                p_content_type => l_content_type);
end;  '
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.dbflow.deploy',
      p_pattern            => 'compile',
      p_method             => 'POST',
      p_name               => 'file_name',
      p_bind_variable_name => 'fname',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => 'reletive filename');      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'com.dbflow.deploy',
      p_pattern        => 'impapp',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.dbflow.deploy',
      p_pattern        => 'impapp',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'begin
  rest_compile.import_app_rest( p_app_file_content   => :body_text,
                                p_to_workspace       => :target_workspace,
                                p_to_schema          => :target_schema,
                                p_application_id     => :target_app_id);
end;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.dbflow.deploy',
      p_pattern            => 'impapp',
      p_method             => 'POST',
      p_name               => 'target_app_id',
      p_bind_variable_name => 'target_app_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => 'ID of the new APP');      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.dbflow.deploy',
      p_pattern            => 'impapp',
      p_method             => 'POST',
      p_name               => 'target_schema',
      p_bind_variable_name => 'target_schema',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => 'Name of the assigne schema the app should use');      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.dbflow.deploy',
      p_pattern            => 'impapp',
      p_method             => 'POST',
      p_name               => 'target_workspace',
      p_bind_variable_name => 'target_workspace',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => 'Name of the workspace to import the app to');      


  COMMIT; 
END;
/
